# Generated by Django 2.2.16 on 2021-09-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20210911_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
